### ISSUE TITLE
Remix demo

### ISSUE THREAD

**Issue by jehrhardt** [jehrhardt/supapasskeys-remix-demo#1]
Remix is a popular React based project. A demo project will show the usage of Supapasskeys with Remix.

### Non-goals
Since there is no SDK for Supapasskeys yet, the demo will only show an integration with standard solutions.

### Solution
The demo combines Supabase Auth with magic links and Supapasskeys. The combination covers the following scenarios:

- Sign-up with magic link
- Register a Passkey
- Sign-in with Passkey
- 2FA JWT with Passkey
- List and delete Passkeys

#### Local setup
Local Supabase setup and local Supapasskeys setup with Docker are provided.

### Todos

- [ ] Add local Supabase
- [ ] Add local Supapasskeys
- [ ] Documentation in README
- [ ] Add Magic Link Sign-up
- [ ] Add Passkey registration
- [ ] Add Passkey authentication
- [ ] Add Passkey management

### Dependencies

- jehrhardt/supapasskeys#63
- jehrhardt/supapasskeys#64
- jehrhardt/supapasskeys-cli#1
- jehrhardt/supapasskeys#67

**Comment by jehrhardt** [comment]
As described in https://github.com/jehrhardt/supapasskeys/discussions/91, examples will be added to [jehrhardt/supapasskeys](https://github.com/jehrhardt/supapasskeys).
